// <auto-generated />
using System;
using AiReadinessAssessment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiReadinessAssessment.Infrastructure.Migrations
{
    [DbContext(typeof(AiReadinessAssessmentDbContext))]
    [Migration("20260417160721_AddOrganizations")]
    partial class AddOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AiReadinessAssessment.Domain.InitialAssessment.BaselineAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrganizationId");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartedAt");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("AiReadinessAssessment.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("AiReadinessAssessment.Domain.InitialAssessment.BaselineAssessment", b =>
                {
                    b.OwnsMany("AiReadinessAssessment.Domain.InitialAssessment.CategoryAssessment", "CategoryAssessments", b1 =>
                        {
                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("Id");

                            b1.Property<int>("Category")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Category");

                            b1.Property<int>("MaturityLevel")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaturityLevel");

                            b1.Property<string>("Observations")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Observations");

                            b1.HasKey("AssessmentId", "Id");

                            b1.ToTable("AssessmentCategories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");

                            b1.OwnsMany("AiReadinessAssessment.Domain.InitialAssessment.AssessmentResponse", "Responses", b2 =>
                                {
                                    b2.Property<Guid>("AssessmentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("CategoryAssessmentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Id");

                                    b2.Property<string>("Answer")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Answer");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("QuestionId");

                                    b2.Property<DateTime>("RecordedAt")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("RecordedAt");

                                    b2.HasKey("AssessmentId", "CategoryAssessmentId", "Id");

                                    b2.ToTable("AssessmentResponses", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AssessmentId", "CategoryAssessmentId");
                                });

                            b1.Navigation("Responses");
                        });

                    b.OwnsMany("AiReadinessAssessment.Domain.InitialAssessment.Recommendation", "Recommendations", b1 =>
                        {
                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("Id");

                            b1.Property<int>("Category")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Category");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.Property<int>("Priority")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Priority");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Title");

                            b1.HasKey("AssessmentId", "Id");

                            b1.ToTable("Recommendations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.Navigation("CategoryAssessments");

                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
